version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo ls Terraform/front-end
      - ls Terraform/front-end
      - cd Terraform/front-end
      - rm -rf node_modules
      - rm -rf package-lock.json
      - echo installing "node modules"
      - npm install

  pre_build:
    commands:
      - echo cd Terraform/front-end
      - rm -rf node_modules
      - rm -rf package-lock.json
      - echo pwd && ls -la
      - pwd
      - ls -la
      - echo installing source npm dependencies ...
      - npm install
      - npm i eslint-config-react-app
      - echo making build folder
      - npm run build
      - ls -la
      - echo node --version

  post_build:
    commands:
      - echo deployment completed on `date`

artifacts:
    files:
      - '**/*'
    base-directory: './build'  