version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd ./Terraform/front-end
      - mkdir build
      - rm -rf ./node_modules
      - rm -rf .package-lock.json
      - ls -la
      - echo installing "node modules"
      - npm install

  pre_build:
    commands:
      - echo installing source npm dependencies ...
      - echo making build folder
      - npm run build
      - ls -la

  post_build:
    commands:
      - echo deployment completed on `date`

artifacts:
    files:
      - '**/*'
    base-directory: './build'  