version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo pwd && ls -la
      - pwd
      - ls -la
      - echo installing "node modules"
      - npm install

  pre_build:
    commands:
      - echo "WTF"
      - echo ls -la
      - pwd
      - ls -la
      - echo cd Terraform/front-end
      - cd Terraform/front-end
      - echo installing source npm dependencies ...
      - echo making build folder
      - npm run build
      - ls -la
      - echo node --version

  post_build:
    commands:
      - echo deployment completed on `date`

artifacts:
    files:
      - '**/*'
    base-directory: './build'  